### ISSUE TITLE
chemical potential range

### ISSUE THREAD

**Issue by similt** [kumagai-group/pydefect#11]
1. I want to get chemical potential of atomic species for formation energy calculation of Sb doped Rb3InCl6. From the generated chemical potential diagram (Rb3InCl6) and from target_vertices.yaml, I can see impurity_phases: Sb 
and chemical potential of Sb is zero. Can I proceed the formation energy calculation at this point in cpd? 
3. When I generate supercell with defect, I am getting the error: 
    pydefect.util.error_classes.NotPrimitiveError
How can I get rid of this error?

**Comment by yuuukuma** [comment]
1. The chemical potentials are relative values wrt the standard states. So, zero is fine if the competing phase is Sb substance.
2. Which kind of unitcell do you use? Please try to run 
vise si -p ../unitcell/structure_opt/POSCAR -primitive

**Comment by similt** [comment]
My unit cell was not primitive as I used the unit cell from experimental structure. 
"vise si -p ../unitcell/structure_opt/POSCAR -primitive" could generate primitive and I could generate defect structures. Thank you.
