### ISSUE TITLE
Can't instantiate abstract class GkfoCorrection with abstract methods correction_dict

### ISSUE THREAD

**Issue by Tangshi3** [kumagai-group/pydefect#14]
I find a issue, when i use the command 
"pydefect_util gkfo -u ../../../unitcell/unitcell.yaml -iefnv ../correction.json -icr ../calc_results.json -fcr calc_results.json -cd 1" in Tutorial for calculation of vertical transition level
i get the error, "Can't instantiate abstract class GkfoCorrection with abstract methods correction_dict". I guess that the code of "gkfo_correction.py" do not have implementation of the method "correction_dict", so i fixed this bug by adding following code:
    @property
    def correction_dict(self):
            return self.__repr__()
Then it worked, the results look like reasonable.  I donot know the details of pydefect code. Please fix this bug offcially.

By the way, "assert final_calc_results.structure == initial_calc_results.structure" maybe too "strick". The static calculation of VASP cannot keep the POSCAR and CONTCAR total same, there is tiny difference， which is probably related with "Floating point precision". Can blogger consider this situation to make pydefect robust.

**Comment by yuuukuma** [comment]
Thank you for using my code and letting me know the bug. 
I've fixed the issue. Could you please try the latest version?

And I also removed the assertion. Please also check it if you have a chance.
