### ISSUE TITLE
Materials Project and pydefect compatibility 

### ISSUE THREAD

**Issue by similt** [kumagai-group/pydefect#17]
After an upgrade in the Material Project API, pydefect is not working: 
Could you resolve the below issue? 

The example program 
pydefect_vasp mp -e Mg Al O --e_above_hull 0.0005
is giving error: 
  INFO: -- Settings from vise.yaml:
   INFO:
   INFO: -- Settings from pydefect.yaml:
   INFO:
   INFO: Note that you're using the newer MPRester.
Traceback (most recent call last):
  File "/home/xxx/Downloads/anaconda3/lib/python3.9/site-packages/pydefect/util/mp_tools.py", line 32, in __init__
    self.materials = m.query(
  File "/home/xxx/Downloads/anaconda3/lib/python3.9/site-packages/mp_api/client/mprester.py", line 1420, in query
    raise NotImplementedError(
NotImplementedError:
            The MPRester().query method has been replaced with the MPRester().summary.search method.
            Note this method also no longer supports direct MongoDB-type queries. For more information,
            please see the new documentation.

During handling of the above exception, another exception occurred:

......

File "/home/xxx/Downloads/anaconda3/lib/python3.9/site-packages/mp_api/client/core/client.py", line 870, in _submit_request_and_process
    raise MPRestError(
mp_api.client.core.client.MPRestError: REST query returned with error status code 422 on URL https://api.materialsproject.org/materials/summary/?energy_above_hull_min=-1e-05&energy_above_hull_max=0.0005&exclude_elements=Tm%2CAc%2CMc%2CC%2CTh%2COg%2CZr%2CH%2CFl%2CK%2CHo%2CSr%2CDb%2CLa%2CP%2CS%2CSg%2CMt%2CGa%2CRg%2CN%2CI%2CIn%2CBe%2CNo%2CFr%2CTc%2CRb%2CAg%2CXe%2CB%2CU%2CNa%2CKr%2CBr%2CTs%2CMd%2CCo%2CSb%2CAt%2CBi%2CCm%2CPo%2CRa%2CSe%2CTi%2CPd%2CBa%2CCr%2CCe%2CZn%2CTl%2CSn%2CLr%2CCa%2CY%2CLu%2CV%2CNe%2CYb%2CF%2CTb%2CRn%2CCn%2CAm%2CLi%2CNb%2CCd%2CMn%2CSi%2CNp%2CLv%2CGd%2CHs%2CMo%2CHg%2CPm%2CRh%2CPu%2CPa%2CGe%2CCl%2CDy%2CCu%2CHe%2CSc%2CBk%2CAs%2CFe%2CTa%2CPb%2CPt%2CFm%2CIr%2CAu%2CSm%2CHf%2CCf%2CNd%2CRu%2CNi%2CRe%2CPr%2CNh%2CDs%2CEs%2CW%2CBh%2CEr%2CRf%2COs%2CCs%2CEu%2CTe%2CAr&_limit=1000&_fields=material_id%2Cformula_pretty%2Cstructure%2Csymmetry%2Cband_gap%2Ctotal_magnetization%2Ctypes_of_magnetic_species with message:
exclude_elements - String should have at most 15 characters

**Comment by yuuukuma** [comment]
Thank you for your information.
Now the issue should be fixed. 
Please use the newer PMG_MAPI_KEY, and upgrade pydefect, vise, and mp-api.
Let me know if you still have problems.

**Comment by similt** [comment]
Thanks for the quick update. 
I have still another error as shown below for the below command: 

pydefect_vasp mp -e Mg Al O --e_above_hull 0.0005
   INFO: -- Settings from vise.yaml:
   INFO: 
   INFO: -- Settings from pydefect.yaml:
   INFO: 
Traceback (most recent call last):
  File "/home/xxx/Downloads/miniconda3/bin/pydefect_vasp", line 5, in <module>
    from pydefect.cli.vasp.main_vasp import main
  File "/home/xxx/Downloads/miniconda3/lib/python3.11/site-packages/pydefect/cli/vasp/main_vasp.py", line 11, in <module>
    from pydefect.cli.vasp.main_vasp_functions import make_defect_entries, \
  File "/home/xxx/Downloads/miniconda3/lib/python3.11/site-packages/pydefect/cli/vasp/main_vasp_functions.py", line 23, in <module>
    from pydefect.util.mp_tools import MpQuery
  File "/home/xxx/Downloads/miniconda3/lib/python3.11/site-packages/pydefect/util/mp_tools.py", line 19, in <module>
    with open(mp_data_file, "r") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/xxx/Downloads/miniconda3/lib/python3.11/site-packages/pydefect/util/MPID_elements_10th_Jan_2024.json'

**Comment by yuuukuma** [comment]
Sorry. Please upgrade pydefect again.

**Comment by similt** [comment]
Thank you for the quick support. Again there is a small problem. 
pydefect_vasp mp -e Mg Al O --e_above_hull 0.0005 
generates only pure phases, Al_mp-143 and Mg_mp-153 and mol_O2 directories. Not creating competing materials like MgAl2O3. Could you correct this?

**Comment by yuuukuma** [comment]
Yes, I fixed it. Please upgrade pydefect again.

**Comment by similt** [comment]
Thanks a lot for fixing the problem.
