### ISSUE TITLE
About ‘pydefect s’ command

### ISSUE THREAD

**Issue by pfwan** [kumagai-group/pydefect#2]
We found that Si (mp-149) can expand into square cells, but GaN(mp-804) can not expand into square cells. Most of the calculations about the point defects in GaN use square cells（96 atoms or 128 atoms）. Is it necessary to establish the supercell manually for some structures? We don't know if pydefect can build an approximate square cell structure for all structures.

**Comment by yuuukuma** [comment]
The squared cell for hexagonal lattice breaks the symmetry, which generates several problems. Therefore, it is prohibited to be generated automatically. However, if you want to use it, you can make it by yourself.

**Comment by pfwan** [comment]
Thanks for your reply！
Pydefect can automatically recommend the charge state of defects. This is a very useful function, especially for calculating unknown defects. Is there any basis for this process?
We found that ‘ supercell.json ‘’file contains oxidation_ State and electronegativity. Whether it is related to these two parameters and how it is determined?


发件人: yuuukuma<mailto:notifications@github.com>
发送时间: 2021年3月8日 13:31
收件人: kumagai-group/pydefect<mailto:pydefect@noreply.github.com>
抄送: pfwan<mailto:pfwan1994@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [kumagai-group/pydefect] About ‘pydefect s’ command (#2)


The squared cell for hexagonal lattice breaks the symmetry, which generates several problems. Therefore, it is prohibited to be generated automatically. However, if you want to use it, you can make it by yourself.

―
