### ISSUE TITLE
typo in `setup.py` prevents CLI from working

### ISSUE THREAD

**Issue by joebesity** [kumagai-group/pydefect#3]
line 36 in `setup.py` is:
```
'pydefect = pydefect.cli.vasp.main:main',
```

however, `main.py` doesn't exist - instead this should be `main_vasp.py`. Correcting line 36 to
```
'pydefect = pydefect.cli.vasp.main_vasp:main',
```
installs correctly, allowing `pydefect -h` to function properly. 

not sure yet if this will break any other CLI functionality but will reply to this issue if this is the case.

**Comment by yuuukuma** [comment]
Thank you, @joebesity !
Yes, the setup.py was wrong, and I fixed it.

However, the current manual is not compatible with the latest pydefect.
I don't have enough time to update it now, but will fix it as soon as possible.

**Comment by yuuukuma** [comment]
@joebesity 
Today, I updated the manual. Let me know when you're in trouble with new manual.
