### ISSUE TITLE
invalid choice

### ISSUE THREAD

**Issue by viridibang** [kumagai-group/pydefect#4]
Hi.

When I follow step3 (3. Gathering unitcell information related to point-defect calculations) in the online manual(https://kumagai-group.github.io/pydefect/tutorial.html#gathering-unitcell-information-related-to-point-defect-calculations), the error appeared as below.

pydefect u --vasprun_band band/vasprun.xml --outcar_band band/OUTCAR --outcar_dielectric_clamped dielectric/OUTCAR --outcar_dielectric_ionic dielectric/OUTCAR

usage: pydefect [-h]
                {standard_and_relative_energies,sre,cpd_and_vertices,cv,plot_cpd,pc,supercell,s,append_interstitial,ai,pop,pi,defect_set,ds,defect_structure_info,dsi,efnv,band_edge_states,bes,defect_energy_infos,dei,defect_energy_summary,des,calc_summary,cs,plot_defect_formation_energy,pe}
                ...
pydefect: error: invalid choice: 'u' (choose from 'standard_and_relative_energies', 'sre', 'cpd_and_vertices', 'cv', 'plot_cpd', 'pc', 'supercell', 's', 'append_interstitial', 'ai', 'pop', 'pi', 'defect_set', 'ds', 'defect_structure_info', 'dsi', 'efnv', 'band_edge_states', 'bes', 'defect_energy_infos', 'dei', 'defect_energy_summary', 'des', 'calc_summary', 'cs', 'plot_defect_formation_energy', 'pe')

If you don't mind, could you suggest the solution to this problem?

Best,
Bang

**Comment by yuuukuma** [comment]
Hi Bang,

Yes, your report is true.
I have made drastic changes for vise and pydefect without backward compatibility.
As such, I need to update the manuals but have had no time to do so.

I try to spare time for the updates, so please wait for a while.
I will let you know when it's done.

Best,
Yu Kumagai

**Comment by yuuukuma** [comment]
@viridibang 

Today, I updated the manual. Let me know when you're in trouble with new manual.
