### ISSUE TITLE
KeyError: 'MgAl2O4'

### ISSUE THREAD

**Issue by Arindamsannyal** [kumagai-group/pydefect#8]
Dear Sir

I am trying to calculate defect formation energy by following the tutorial on pydefect on MgAl2O4 system as provided in the following link

https://kumagai-group.github.io/pydefect/tutorial.html#

In Step 4 of the Calculation of competing phases, after the VASP calculation, I was able to generate the standard_energies.yaml and relative_energies.yaml files. However, when I tried the 'pydefect cv -t MgAl2O4' command to generate the chemical potential diagram, it gives a key error as 'KeyError: 'MgAl2O4''. I have attached the screenshot of the error. Can you please suggest to me how to resolve the error?

Thank you very much. 

Best regards
Arindam Sannyal

![Capture](https://user-images.githubusercontent.com/33083005/199175166-a7481b93-d4d6-41da-97b7-b6a682c845be.JPG)

**Comment by yuuukuma** [comment]
Dear Arindam Sannyal,

thank you for your post.
Could you check if your **relative_energies.yaml** includes "MgAl2O4"?

Here is an example of mine.
```
Al2O3: -3.1489629
Mg17Al12: -0.021573085977011353
MgAl2: -0.011912545555555099
MgAl2O4: -3.0959495723809525
MgO: -2.8267036658333335
```

**Comment by Arindamsannyal** [comment]
Dear Sir

Thank you very much for your prompt response. Yes, Sir, my relative_energies.yaml file includes the "MgAl2O4" as in the attached figure.

![Capture](https://user-images.githubusercontent.com/33083005/199180653-ec32f45f-93b2-49f0-8e1a-1781a7755d2b.JPG)

**Comment by yuuukuma** [comment]
Okay, then MgAl2O4 should not be energetically stable at 0K in your calculations.
In other word, it does not appear in the chemical potential diagram.

Could you artificially reduce the energy of MgAl2O4 by -1.0 eV for example, and run the same command?

I should show an adequate error message.

**Comment by Arindamsannyal** [comment]
Dear Sir

As you suggested, I have artificially reduced the energy of MgAl2O4 by -1.0 eV. 
![Capture](https://user-images.githubusercontent.com/33083005/199193459-aa52795a-7919-496f-bb9f-a6bb862a25f5.JPG)

Now the 'pydefect cv -t MgAl2O4' command gives the AssertionError as follows
![Capture](https://user-images.githubusercontent.com/33083005/199193546-69af9884-862d-4c92-9019-1d125eac8a8c.JPG)

Sir, I would like to mention that the energies calculated from my VASP calculations deviate by ~0.3 eV from those shown in the tutorial. Thank you very much.

Best regards
Arindam Sannyal

**Comment by yuuukuma** [comment]
Could you remove H3N and NO2, please?

**Comment by Arindamsannyal** [comment]
Dear Sir

Removing the H3N and NO2 successfully generates the chemical potential diagram. Thank you very much, Sir.

Best regards
Arindam Sannyal
